name: API tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  newman:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4           # clone le dépôt

    - uses: actions/setup-node@v4         # installe Node 18
      with:
        node-version: 18

    - name: Install Newman & reporter
      run: npm install -g newman newman-reporter-htmlextra

    - name: Run Postman tests
      run: |
        mkdir -p newman
        newman run API-demo-tests.postman_collection.json \
               -e API-demo-tests.postman_environment.json \
               -d data.csv \
               -r cli,htmlextra \
               --reporter-htmlextra-export newman/report.html

    - name: Upload HTML report
      uses: actions/upload-artifact@v4
      with:
        name: newman-report
        path: newman/report.html
